// Builds wallet/assets/vendor/crypto.js from the pinned libraries in package.json.
// Run after changing a version: npm install && npm run build, then commit the bundle.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, "../../wallet/assets/vendor/crypto.js");
const pkg = JSON.parse(readFileSync(path.join(here, "package.json"), "utf8"));

await build({
  entryPoints: [path.join(here, "vendor-entry.js")],
  bundle: true,
  format: "esm",
  target: "es2022",
  minify: false,
  legalComments: "inline",
  outfile: out,
});

const versions = Object.entries(pkg.dependencies)
  .map(([n, v]) => `${n}@${v}`)
  .join(", ");
const body = readFileSync(out, "utf8");
const header = `// Generated by tools/wallet-build (npm run build) — do not edit by hand.\n// Bundled from: ${versions}\n`;
writeFileSync(out, header + body);
const digest = createHash("sha256").update(readFileSync(out)).digest("base64");
console.log(`wrote ${path.relative(path.join(here, "../.."), out)} (${(body.length / 1024).toFixed(0)} kB)`);
console.log(`sha256-${digest}`);
